### ISSUE TITLE
Server compatibility?

### ISSUE THREAD

**Issue by NotoriusQ** [Azmalent/potion-snowballs#1]
I'm so happy you updated to 1.16.4!!

I'm using Forge Latest 35.1.13. 
I also have 100+ other mods installed too hahaha
I didn't see anything in the description about it being client-only?

> [22.12 22:34:22] [Server] [modloading-worker-16/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: potionsnowballs, class azmalent.potionsnowballs.PotionSnowballs
[22.12 22:34:22] [Server] java.lang.BootstrapMethodErrorjava.lang.NoSuchMethodError: azmalent.potionsnowballs.PotionSnowballs.clientSetup(Lnet/minecraftforge/fml/event/lifecycle/FMLClientSetupEvent;)V
[22.12 22:34:22] [Server] 	at azmalent.potionsnowballs.PotionSnowballs.<init>(PotionSnowballs.java:68) ~[potionsnowballs:1.2.{re:classloading,pl:runtimedistcleaner:A}
[22.12 22:34:22] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.{re:classloading}
[22.12 22:34:22] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
[22.12 22:34:22] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_{}
[22.12 22:34:22] [Server] Caused byjava.lang.NoSuchMethodError: azmalent.potionsnowballs.PotionSnowballs.clientSetup(Lnet/minecraftforge/fml/event/lifecycle/FMLClientSetupEvent;)V
[22.12 22:34:22] [Server] 	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_{}
[22.12 22:34:22] [Server] 	... more

**Comment by Azmalent** [comment]
This issue was fixed in the latest version.
